<?php
require_once 'includes/bootstrap.php';require_once 'includes/config.php';require_once 'includes/dean-auth.php';require_dean();require_once 'includes/portal-layout.php';
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    csrf_require_valid($_POST['csrf_token']??'');
    try{$dbh->beginTransaction();$row=cbe_one($dbh,"SELECT id FROM tblparentsms WHERE id=? AND Status='failed' FOR UPDATE",[(int)($_POST['id']??0)]);
        if(!$row)throw new DomainException('Only a confirmed failed attempt can be retried. Verify uncertain attempts with the provider.');
        academic_query($dbh,"UPDATE tblparentsms SET Status='pending' WHERE id=?",[$row['id']]);audit_log($dbh,'parent_sms_retry','tblparentsms',$row['id'],'Confirmed failed attempt queued for retry');$dbh->commit();header('Location: dean-sms-deliveries.php');exit;
    }catch(Throwable $e){if($dbh->inTransaction())$dbh->rollBack();error_log($e->getMessage());$error=$e instanceof DomainException?$e->getMessage():'Could not queue retry.';}
}
$page=portal_page($_GET);$status=is_string($_GET['status']??null)?$_GET['status']:'';$allowed=['pending','processing','accepted','failed','uncertain','skipped'];if(!in_array($status,$allowed,true))$status='';
$rows=cbe_rows($dbh,"SELECT q.*,u.FullName,s.RollId FROM tblparentsms q JOIN tblusers u ON u.id=q.ParentId JOIN tblstudents s ON s.StudentId=q.StudentId WHERE (?='' OR q.Status=?) ORDER BY q.id DESC LIMIT 26 OFFSET ".(($page-1)*25),[$status,$status]);
portal_start('Parent SMS deliveries','dean');portal_alert($error);?><section class="parent-card"><p>Accepted means the SMS provider accepted the request. Processing or uncertain attempts need provider verification before any resend.</p><form method="get" class="form-inline"><label for="status">Status</label> <select id="status" name="status" class="form-control"><option value="">All</option><?php foreach($allowed as $option)echo '<option '.($status===$option?'selected ':'').'value="'.$option.'">'.ucfirst($option).'</option>';?></select> <button class="btn btn-default">Filter</button></form><div class="table-responsive"><table class="table"><thead><tr><th>Guardian / learner</th><th>Recipient</th><th>Status</th><th>Attempts</th><th>Attempted</th><th>Provider reference / error</th><th>Action</th></tr></thead><tbody><?php foreach(array_slice($rows,0,25) as $row){?><tr><td><?= academic_h($row['FullName'].' / '.$row['RollId']) ?></td><td><?= academic_h($row['Destination']) ?></td><td><?= academic_h($row['Status']) ?></td><td><?= (int)$row['Attempts'] ?></td><td><?= academic_h($row['AttemptedAt']) ?></td><td><?= academic_h(($row['ProviderReference']??'').' '.($row['ErrorMessage']??'')) ?></td><td><?php if($row['Status']==='failed'){?><form method="post"><?php csrf_field();?><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button class="btn btn-default btn-sm">Retry failed attempt</button></form><?php }?></td></tr><?php }if(!$rows)echo '<tr><td colspan="7">No publication SMS messages.</td></tr>';?></tbody></table></div><?php portal_pagination($page,count($rows)>25,['status'=>$status]);?></section><?php portal_end('dean'); ?>
