<?php
require_once 'includes/bootstrap.php';require_once 'includes/config.php';require_once 'includes/parent-auth.php';require_once 'includes/portal-layout.php';
$parent=require_parent();$studentId=filter_var($_GET['student']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);
$student=parent_child($dbh,$parent['id'],$studentId?:0);
$examId=filter_var($_GET['exam']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>0]]);
$classId=filter_var($_GET['class']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>0]]);
if($examId===false||$classId===false){http_response_code(404);exit('Report unavailable.');}
$publication=null;$rows=[];
if($examId){
    $publication=cbe_one($dbh,'SELECT p.*,e.ExamName,e.AcademicYearId,e.TermId,e.MaximumMarks,y.AcademicYear,t.TermName,c.ClassName,c.Section,c.ClassNameNumeric GradeNumber
        FROM tblresultpublications p JOIN tblexams e ON e.id=p.ExamId JOIN tblclasses c ON c.id=p.ClassId
        JOIN tblacademicyears y ON y.id=e.AcademicYearId JOIN tblterms t ON t.id=e.TermId
        WHERE p.ExamId=? AND p.ClassId=? AND EXISTS(SELECT 1 FROM tblresult r WHERE r.StudentId=? AND r.ClassId=p.ClassId AND r.ExamId=p.ExamId)',[$examId,$classId,$studentId]);
    if(!$publication){http_response_code(404);exit('Report unavailable.');}
    $rows=cbe_rows($dbh,'SELECT sub.SubjectName,r.marks FROM tblresult r JOIN tblsubjects sub ON sub.id=r.SubjectId WHERE r.StudentId=? AND r.ClassId=? AND r.ExamId=? ORDER BY sub.SubjectName',[$studentId,$classId,$examId]);
}
portal_start($examId?'Published report card':'Academic history');
?><div class="report-actions"><a class="btn btn-default" href="parent-dashboard.php">My children</a> <a class="btn btn-default" href="parent-report.php?student=<?= (int)$studentId ?>">All reports</a><?php if($examId){ ?> <button class="btn btn-primary" onclick="window.print()">Print / Save PDF</button><?php } ?></div>
<section class="parent-card"><h2><?= academic_h(getenv('SCHOOL_NAME')?:'Senior School') ?></h2><p><?= academic_h(getenv('SCHOOL_ADDRESS')?:'') ?></p><div class="report-meta"><p><strong>Learner:</strong> <?= academic_h($student['StudentName']) ?></p><p><strong>Admission:</strong> <?= academic_h($student['RollId']) ?></p>
<?php if($publication){
$placement=cbe_one($dbh,'SELECT p.Name Pathway,t.Name Track FROM tblstudentpathways a JOIN tblpathways p ON p.id=a.PathwayId LEFT JOIN tblpathwaytracks t ON t.id=a.TrackId WHERE a.StudentId=? AND a.AcademicYearId=? AND a.ClassId=? ORDER BY a.Status DESC,a.id DESC LIMIT 1',[$studentId,$publication['AcademicYearId'],$classId]);
$teacher=academic_query($dbh,'SELECT u.FullName FROM tblclassteacherassignments a JOIN tblusers u ON u.id=a.TeacherId WHERE a.ClassId=? AND a.AcademicYearId=? ORDER BY a.Status DESC,a.id DESC LIMIT 1',[$classId,$publication['AcademicYearId']])->fetchColumn();
foreach(['Grade'=>$publication['GradeNumber'],'Class'=>$publication['ClassName'].' '.$publication['Section'],'Pathway'=>$placement['Pathway']??'Not recorded','Track'=>$placement['Track']??'Not recorded','Academic year'=>$publication['AcademicYear'],'Term'=>$publication['TermName'],'Examination'=>$publication['ExamName'],'Class teacher'=>$teacher?:'Not assigned','Published'=>$publication['PublishedAt']] as $key=>$value)echo '<p><strong>'.academic_h($key).':</strong> '.academic_h($value).'</p>'; }
?></div><?php if($publication){$scales=json_decode($publication['GradeScale']??'[]',true)?:[];$total=0;?><div class="table-responsive"><table class="table table-bordered"><thead><tr><th>Subject</th><th>Score</th><th>Maximum</th><th>School performance level</th><th>Descriptor</th></tr></thead><tbody><?php foreach($rows as $row){$total+=(float)$row['marks'];$percentage=round(100*(float)$row['marks']/(float)$publication['MaximumMarks'],2);$grade=null;foreach($scales as $scale)if($percentage>=(float)$scale['MinMark']&&$percentage<=(float)$scale['MaxMark']){$grade=$scale;break;}?><tr><td><?= academic_h($row['SubjectName']) ?></td><td><?= academic_h($row['marks']) ?></td><td><?= academic_h($publication['MaximumMarks']) ?></td><td><?= academic_h($grade['Grade']??'Not configured') ?></td><td><?= academic_h($grade['Remark']??'') ?></td></tr><?php } ?></tbody></table></div><p><strong>Overall score:</strong> <?= academic_h($total) ?> / <?= academic_h(count($rows)*(float)$publication['MaximumMarks']) ?> (<?= number_format(100*$total/(count($rows)*(float)$publication['MaximumMarks']),2) ?>%)</p><p class="help-block">Performance descriptors follow the school's configured assessment scale. Subjects follow this learner's registrations.</p>
<?php foreach(cbe_rows($dbh,"SELECT c.CommentText,u.FullName FROM tblteachercomments c JOIN tblusers u ON u.id=c.TeacherId WHERE c.StudentId=? AND c.ClassId=? AND c.ExamId=? AND c.Status='published' ORDER BY c.id",[$studentId,$classId,$examId]) as $comment){?><h3><?= academic_h($comment['FullName']) ?></h3><p><?= nl2br(academic_h($comment['CommentText'])) ?></p><?php }
}else{
$page=portal_page($_GET);$history=cbe_rows($dbh,'SELECT p.*,e.ExamName,y.AcademicYear,t.TermName,ROUND(100*AVG(r.marks)/e.MaximumMarks,2) AverageScore FROM tblresultpublications p JOIN tblexams e ON e.id=p.ExamId JOIN tblacademicyears y ON y.id=e.AcademicYearId JOIN tblterms t ON t.id=e.TermId JOIN tblresult r ON r.ExamId=p.ExamId AND r.ClassId=p.ClassId AND r.StudentId=? GROUP BY p.id,e.id,y.id,t.id ORDER BY p.PublishedAt DESC,p.id DESC LIMIT 26 OFFSET '.(($page-1)*25),[$studentId]);
?><div class="table-responsive"><table class="table"><thead><tr><th>Year / Term</th><th>Examination</th><th>Average</th><th>Published</th><th>Report</th></tr></thead><tbody><?php foreach(array_slice($history,0,25) as $h){?><tr><td><?= academic_h($h['AcademicYear'].' / '.$h['TermName']) ?></td><td><?= academic_h($h['ExamName']) ?></td><td><?= academic_h($h['AverageScore']) ?>%</td><td><?= academic_h($h['PublishedAt']) ?></td><td><a href="?student=<?= (int)$studentId ?>&exam=<?= (int)$h['ExamId'] ?>&class=<?= (int)$h['ClassId'] ?>">View report</a></td></tr><?php }if(!$history)echo '<tr><td colspan="5">No published reports yet.</td></tr>';?></tbody></table></div><?php portal_pagination($page,count($history)>25,['student'=>$studentId]); } ?></section><?php portal_end(); ?>
