<?php
require_once 'includes/bootstrap.php';require_once 'includes/config.php';require_once 'includes/parent-auth.php';require_once 'includes/portal-layout.php';
$parent=require_parent();$children=parent_children($dbh,$parent['id']);portal_start('My children');
$unread=(int)academic_query($dbh,'SELECT COUNT(*) FROM tblparentnotifications n JOIN tblparentstudents ps ON ps.ParentId=n.ParentId AND ps.StudentId=n.StudentId AND ps.Status=1 WHERE n.ParentId=? AND n.ReadAt IS NULL',[$parent['id']])->fetchColumn();
?><p>Welcome, <?= academic_h($parent['FullName']) ?>. <a href="parent-notifications.php"><?= $unread ?> unread notifications</a></p><div class="parent-grid">
<?php foreach($children as $child){ ?><section class="parent-card"><h2><?= academic_h($child['StudentName']) ?></h2><p><?= academic_h($child['RollId'].' · '.$child['ClassName'].' '.$child['Section']) ?></p>
<?php $exams=cbe_rows($dbh,'SELECT p.ExamId,p.ClassId,p.PublishedAt,e.ExamName,y.AcademicYear,t.TermName FROM tblresultpublications p JOIN tblexams e ON e.id=p.ExamId JOIN tblacademicyears y ON y.id=e.AcademicYearId JOIN tblterms t ON t.id=e.TermId WHERE EXISTS(SELECT 1 FROM tblresult r WHERE r.StudentId=? AND r.ClassId=p.ClassId AND r.ExamId=p.ExamId) ORDER BY p.PublishedAt DESC,p.id DESC LIMIT 5',[$child['StudentId']]);
foreach($exams as $exam){ ?><p><a href="parent-report.php?student=<?= (int)$child['StudentId'] ?>&exam=<?= (int)$exam['ExamId'] ?>&class=<?= (int)$exam['ClassId'] ?>"><?= academic_h($exam['AcademicYear'].' · '.$exam['TermName'].' · '.$exam['ExamName']) ?></a><br><small>Published <?= academic_h($exam['PublishedAt']) ?></small></p><?php } if(!$exams)echo '<p>No results have been published yet.</p>'; ?><a class="btn btn-default" href="parent-report.php?student=<?= (int)$child['StudentId'] ?>">Academic history</a> <a class="btn btn-default" href="parent-child.php?student=<?= (int)$child['StudentId'] ?>">Learner profile</a> <a class="btn btn-default" href="parent-assessments.php?student=<?= (int)$child['StudentId'] ?>">Assessments</a></section><?php } if(!$children)echo '<section class="parent-card"><p>No active children are linked to this account. Contact the school to verify your guardian links.</p></section>'; ?></div>
<section class="parent-card"><h2>School notices</h2><?php $notices=cbe_rows($dbh,'SELECT noticeTitle,noticeDetails,postingDate FROM tblnotice ORDER BY id DESC LIMIT 10');if(!$notices)echo '<p>No school notices have been posted yet.</p>';foreach($notices as $notice){ ?><article><h3><?= academic_h($notice['noticeTitle']) ?></h3><p><?= nl2br(academic_h($notice['noticeDetails'])) ?></p><small><?= academic_h($notice['postingDate']) ?></small></article><?php } ?></section><?php portal_end(); ?>
