<?php
session_start(); require 'includes/config.php'; require 'includes/csrf.php'; require 'includes/dean-auth.php'; require 'includes/audit.php'; require_once 'includes/academic-assignments.php'; require_dean();
$ready=academic_ready($dbh); $error='';
$year=(int)($_POST['year']??$_GET['year']??academic_year($dbh)); $class=(int)($_GET['class']??0); $student=(int)($_POST['student']??$_GET['student']??0);
if($ready && $_SERVER['REQUEST_METHOD']==='POST') {
    csrf_require_valid($_POST['csrf_token']??'');
    try {
        $dbh->beginTransaction(); academic_register_student($dbh,$student,$year,$_POST['subjects']??[]);
        audit_log($dbh,'student_subjects_updated','tblstudents',$student,'Academic year '.$year); $dbh->commit();
        header('Location: student-subjects.php?'.http_build_query(['year'=>$year,'student'=>$student,'saved'=>1]));exit;
    } catch(Throwable $e) { if($dbh->inTransaction())$dbh->rollBack();$error=$e instanceof DomainException?$e->getMessage():'Unable to save subject registrations.';error_log($e->getMessage()); }
}
$selected=academic_query($dbh,'SELECT s.*,CONCAT(c.ClassName," ",c.Section) ClassLabel FROM tblstudents s JOIN tblclasses c ON c.id=s.ClassId WHERE s.StudentId=? AND s.Status=1',[$student])->fetch(PDO::FETCH_ASSOC);
?>
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Student Subject Combinations | SRMS</title><link rel="stylesheet" href="css/bootstrap.min.css"><link rel="stylesheet" href="css/font-awesome.min.css"><link rel="stylesheet" href="css/main.css"><link rel="stylesheet" href="css/custom.css"></head><body class="top-navbar-fixed"><div class="main-wrapper"><?php include 'includes/topbar.php'; ?><div class="content-wrapper"><div class="content-container"><?php include 'includes/leftbar.php'; ?><div class="main-page"><div class="container-fluid"><h2>Student Subject Combinations</h2><section class="section">
<?php if(!$ready) { ?><div class="alert alert-warning">Apply the teacher relationship migration first.</div><?php } else { ?>
<?php if($error) { ?><div class="alert alert-danger"><?= academic_h($error) ?></div><?php } if(isset($_GET['saved'])) { ?><div class="alert alert-success">Student subjects saved.</div><?php } ?>
<p><a href="manage-subjectcombination.php">Manage subjects offered by each class</a> · <a href="dean-teacher-relationships.php">Teacher Relationships</a></p>
<form method="get" class="panel panel-body"><label>Academic year</label><select name="year" class="form-control"><?php foreach($dbh->query('SELECT * FROM tblacademicyears ORDER BY AcademicYear DESC') as $y) { ?><option value="<?= (int)$y['id'] ?>" <?= (int)$y['id']===$year?'selected':'' ?>><?= academic_h($y['AcademicYear']) ?></option><?php } ?></select>
<label>Filter class</label><select name="class" class="form-control academic-search"><option value="0">All classes</option><?php foreach($dbh->query('SELECT * FROM tblclasses ORDER BY ClassNameNumeric,Section') as $c) { ?><option value="<?= (int)$c['id'] ?>" <?= (int)$c['id']===$class?'selected':'' ?>><?= academic_h($c['ClassName'].' '.$c['Section']) ?></option><?php } ?></select><button class="btn btn-default">Filter</button>
<label>Student</label><select name="student" class="form-control academic-search"><option value="0">Select student</option><?php foreach(academic_query($dbh,'SELECT StudentId,StudentName,RollId FROM tblstudents WHERE Status=1 AND (?=0 OR ClassId=?) ORDER BY StudentName',[$class,$class]) as $s) { ?><option value="<?= (int)$s['StudentId'] ?>" <?= (int)$s['StudentId']===$student?'selected':'' ?>><?= academic_h($s['StudentName'].' ('.$s['RollId'].')') ?></option><?php } ?></select><button class="btn btn-primary">Open Student</button></form>
<?php if($selected) {
$chosen=academic_query($dbh,'SELECT SubjectId FROM tblstudentsubjects WHERE StudentId=? AND ClassId=? AND AcademicYearId=? AND Status=1',[$student,$selected['ClassId'],$year])->fetchAll(PDO::FETCH_COLUMN);
$offered=academic_query($dbh,'SELECT DISTINCT s.id,s.SubjectName FROM tblsubjectcombination c JOIN tblsubjects s ON s.id=c.SubjectId WHERE c.ClassId=? AND c.status=1 ORDER BY s.SubjectName',[$selected['ClassId']])->fetchAll(PDO::FETCH_ASSOC);
?><div class="panel panel-body"><h3><?= academic_h($selected['StudentName']) ?></h3><p><?= academic_h($selected['ClassLabel']) ?></p><form method="post"><?php csrf_field(); ?><input type="hidden" name="year" value="<?= $year ?>"><input type="hidden" name="student" value="<?= $student ?>"><label>Subjects taken by this student</label><select name="subjects[]" multiple size="12" class="form-control academic-search"><?php foreach($offered as $s) { ?><option value="<?= (int)$s['id'] ?>" <?= in_array($s['id'],$chosen)?'selected':'' ?>><?= academic_h($s['SubjectName']) ?></option><?php } ?></select><p class="help-block">Use Ctrl (Windows) or Command (Mac) to select several subjects. Clearing a selection removes that registration for this academic year. Other years are preserved.</p><button class="btn btn-primary">Save Student Subjects</button></form></div><?php } ?>
<div class="panel panel-body"><h4>Active students without subjects in this year</h4><ul><?php foreach(academic_query($dbh,'SELECT s.StudentId,s.StudentName FROM tblstudents s WHERE s.Status=1 AND (?=0 OR s.ClassId=?) AND NOT EXISTS (SELECT 1 FROM tblstudentsubjects ss WHERE ss.StudentId=s.StudentId AND ss.ClassId=s.ClassId AND ss.AcademicYearId=? AND ss.Status=1) ORDER BY s.StudentName',[$class,$class,$year]) as $s) { ?><li><a href="?year=<?= $year ?>&student=<?= (int)$s['StudentId'] ?>"><?= academic_h($s['StudentName']) ?></a></li><?php } ?></ul></div>
<?php } ?></section></div></div></div></div></div><script src="js/jquery/jquery-2.2.4.min.js"></script><script src="js/bootstrap/bootstrap.min.js"></script><script src="js/main.js"></script><script src="js/academic-assignments.js"></script></body></html>
