<?php
require_once 'includes/bootstrap.php';require_once 'includes/config.php';require_once 'includes/teacher-auth.php';require_teacher();require_once 'includes/result-workflow.php';require_once 'includes/portal-layout.php';
$error='';$class=(int)($_POST['ClassId']??$_GET['class']??0);$subject=(int)($_POST['SubjectId']??$_GET['subject']??0);$exam=(int)($_POST['ExamId']??$_GET['exam']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
    csrf_require_valid($_POST['csrf_token']??'');
    try{$dbh->beginTransaction();workflow_subject_save($dbh,teacher_id(),$_POST);$dbh->commit();header('Location: teacher-mark-entry.php?'.http_build_query(['class'=>$class,'subject'=>$subject,'exam'=>$exam,'saved'=>1]));exit;}
    catch(Throwable $e){if($dbh->inTransaction())$dbh->rollBack();error_log($e->getMessage());$error=$e instanceof DomainException?$e->getMessage():'Could not save marks. Please try again.';}
}
$options=cbe_rows($dbh,'SELECT DISTINCT a.ClassId,a.SubjectId,e.id ExamId,c.ClassName,c.Section,s.SubjectName,e.ExamName,y.AcademicYear,t.TermName FROM tblsubjectteacherassignments a
    JOIN tblclasses c ON c.id=a.ClassId AND c.ClassNameNumeric IN (10,11,12) JOIN tblsubjects s ON s.id=a.SubjectId AND s.Status=1
    JOIN tblexams e ON e.AcademicYearId=a.AcademicYearId AND (e.ClassId IS NULL OR e.ClassId=a.ClassId) AND (a.TermId IS NULL OR a.TermId=e.TermId)
    JOIN tblacademicyears y ON y.id=e.AcademicYearId JOIN tblterms t ON t.id=e.TermId WHERE a.TeacherId=? AND a.Status=1 ORDER BY e.id DESC,c.ClassName,s.SubjectName LIMIT 300',[teacher_id()]);
$e=null;$students=[];$editable=false;
if($class&&$subject&&$exam){try{$e=workflow_exam($dbh,$class,$exam);cbe_assignment($dbh,teacher_id(),$class,$subject,$e['AcademicYearId'],$e['TermId']);$students=academic_students($dbh,$class,$subject,$e['AcademicYearId']);try{cbe_exam_writable($dbh,$exam);workflow_editable($dbh,$class,$exam,$subject);$editable=true;}catch(DomainException $locked){$lockMessage=$locked->getMessage();}}catch(DomainException $denied){http_response_code(403);exit('This mark sheet is not assigned to you.');}}
portal_start('Examination mark entry','teacher');portal_alert($error);if(isset($_GET['saved']))portal_alert('Marks saved. Submitted marks remain locked until returned for correction.','success');
?><section class="parent-card"><h2>Assigned mark sheets</h2><div class="table-responsive"><table class="table"><thead><tr><th>Examination</th><th>Class</th><th>Subject</th><th>Mark sheet</th></tr></thead><tbody><?php foreach($options as $option){?><tr><td><?= academic_h($option['AcademicYear'].' / '.$option['TermName'].' / '.$option['ExamName']) ?></td><td><?= academic_h($option['ClassName'].' '.$option['Section']) ?></td><td><?= academic_h($option['SubjectName']) ?></td><td><a href="?class=<?= (int)$option['ClassId'] ?>&subject=<?= (int)$option['SubjectId'] ?>&exam=<?= (int)$option['ExamId'] ?>">Open</a></td></tr><?php }if(!$options)echo '<tr><td colspan="4">No assigned examinations.</td></tr>';?></tbody></table></div></section>
<?php if($e){?><section class="parent-card"><h2><?= academic_h($e['ExamName']) ?> — maximum <?= academic_h($e['MaximumMarks']) ?></h2><?php if(!$editable)portal_alert($lockMessage??'Mark entry is closed.','info');?><form method="post"><?php csrf_field();?><input type="hidden" name="ClassId" value="<?= $class ?>"><input type="hidden" name="SubjectId" value="<?= $subject ?>"><input type="hidden" name="ExamId" value="<?= $exam ?>"><div class="table-responsive"><table class="table"><thead><tr><th>Admission</th><th>Learner</th><th>Score</th></tr></thead><tbody><?php foreach($students as $student){$score=academic_query($dbh,'SELECT marks FROM tblresult WHERE StudentId=? AND ClassId=? AND SubjectId=? AND ExamId=?',[$student['StudentId'],$class,$subject,$exam])->fetchColumn();$value=$error&&isset($_POST['marks'][$student['StudentId']])&&is_scalar($_POST['marks'][$student['StudentId']])?$_POST['marks'][$student['StudentId']]:($score===false?'':$score);?><tr><td><?= academic_h($student['RollId']) ?></td><td><?= academic_h($student['StudentName']) ?></td><td><?php if($editable){?><input aria-label="Score for <?= academic_h($student['StudentName']) ?>" type="number" class="form-control" name="marks[<?= (int)$student['StudentId'] ?>]" min="0" max="<?= academic_h($e['MaximumMarks']) ?>" step="0.01" value="<?= academic_h($value) ?>" required><?php }else echo academic_h($value);?></td></tr><?php }?></tbody></table></div><?php if($editable&&$students){?><button name="action" value="save" class="btn btn-primary">Save draft</button> <button name="action" value="submit" class="btn btn-success">Submit and lock subject marks</button><?php }?></form></section><?php }portal_end('teacher'); ?>
