<?php
require_once __DIR__.'/cbe-academics.php';
function cbe_report($db,$kind,$year,$term=0,$teacher=0,$class=0,$subject=0,$student=0) {
    $p=[$year];$w='a.AcademicYearId=?';
    $periodKinds=['performance','assessments','coverage','interventions','legacy'];
    if($term&&in_array($kind,$periodKinds,true)){$w.=' AND a.TermId=?';$p[]=$term;}
    if($term&&$kind==='assignments'){$w.=' AND (a.TermId IS NULL OR a.TermId=?)';$p[]=$term;}
    if($teacher&&in_array($kind,['performance','assessments','coverage','interventions','assignments'],true)){$w.=' AND a.TeacherId=?';$p[]=$teacher;}
    if($class&&in_array($kind,['performance','assessments','coverage','interventions','assignments','pathways','legacy'],true)){$w.=' AND '.($kind==='interventions'?'s.ClassId':($kind==='legacy'?'r.ClassId':'a.ClassId')).'=?';$p[]=$class;}
    if($subject&&in_array($kind,['performance','assessments','coverage','interventions','assignments','legacy'],true)){$w.=' AND '.($kind==='legacy'?'r.SubjectId':'a.SubjectId').'=?';$p[]=$subject;}
    if($student&&in_array($kind,['performance','interventions','pathways','legacy'],true)){$w.=' AND '.(in_array($kind,['performance','legacy'],true)?'r.StudentId':'a.StudentId').'=?';$p[]=$student;}
    switch($kind) {
      case 'workload':
        $teachers=cbe_rows($db,'SELECT id,FullName FROM tblusers WHERE Status=1 AND Role IN ('.ACADEMIC_TEACHER_ROLES.')'.($teacher?' AND id='.(int)$teacher:'').' ORDER BY FullName');$limits=cbe_one($db,'SELECT * FROM tblacademicsettings WHERE id=1');$rows=[];
        foreach($teachers as $t) {
            $lessons=cbe_rows($db,'SELECT s.SubjectName,CONCAT(c.ClassName," ",c.Section) ClassLabel,COUNT(*) Lessons FROM tblclasstimetableentries e JOIN tblclasses c ON c.id=e.ClassId JOIN tblsubjects s ON s.id=e.SubjectId WHERE e.TeacherId=? AND e.AcademicYearId=? AND (?=0 OR e.TermId=?) AND e.Status NOT IN ("cancelled","archived") GROUP BY s.id,s.SubjectName,c.id,c.ClassName,c.Section',[$t['id'],$year,$term,$term]);
            $total=array_sum(array_column($lessons,'Lessons'));$band=!$term?'SELECT TERM':($limits['WorkloadLow']===null||$limits['WorkloadHigh']===null?'NOT CONFIGURED':($total<$limits['WorkloadLow']?'LOW':($total>$limits['WorkloadHigh']?'HIGH':'NORMAL')));
            $classNames=academic_query($db,'SELECT CONCAT(c.ClassName," ",c.Section) FROM tblclassteacherassignments a JOIN tblclasses c ON c.id=a.ClassId WHERE a.TeacherId=? AND a.AcademicYearId=? AND a.Status=1',[$t['id'],$year])->fetchAll(PDO::FETCH_COLUMN);
            $responsibilities=academic_query($db,'SELECT rt.Name FROM tblteacherresponsibilities r JOIN tblresponsibilitytypes rt ON rt.id=r.ResponsibilityTypeId WHERE r.TeacherId=? AND r.AcademicYearId=? AND r.Status=1',[$t['id'],$year])->fetchAll(PDO::FETCH_COLUMN);
            $rows[]=['Teacher'=>$t['FullName'],'Teaching'=>implode('; ',array_map(fn($l)=>$l['SubjectName'].' / '.$l['ClassLabel'].' — '.$l['Lessons'].' lessons',$lessons)),'Lessons'=>$total,'Class teacher'=>implode(', ',$classNames),'Responsibilities'=>implode(', ',$responsibilities),'Workload'=>$band];
        } return $rows;
      case 'assignments':return cbe_rows($db,"SELECT u.FullName Teacher,s.SubjectName Subject,CONCAT(c.ClassName,' ',c.Section) Class,COALESCE(t.TermName,'Whole year') Term,a.Status,a.CreationDate Assigned,a.EndedAt Ended FROM tblsubjectteacherassignments a JOIN tblusers u ON u.id=a.TeacherId JOIN tblsubjects s ON s.id=a.SubjectId JOIN tblclasses c ON c.id=a.ClassId LEFT JOIN tblterms t ON t.id=a.TermId WHERE $w ORDER BY u.FullName,c.ClassName",$p);
      case 'pathways':return cbe_rows($db,"SELECT s.StudentName Student,s.RollId Admission,CONCAT(c.ClassName,' ',c.Section) Class,p.Name Pathway,t.Name Track,co.Name Combination,a.PlacementSource Source,a.Status,a.AssignedAt Assigned,a.EndedAt Ended FROM tblstudentpathways a JOIN tblstudents s ON s.StudentId=a.StudentId JOIN tblclasses c ON c.id=a.ClassId JOIN tblschoolcombinations co ON co.id=a.CombinationId JOIN tblpathwaytracks t ON t.id=co.TrackId JOIN tblpathways p ON p.id=t.PathwayId WHERE $w ORDER BY s.StudentName,a.id DESC",$p);
      case 'combinations':return cbe_rows($db,'SELECT p.Name Pathway,t.Name Track,c.Name Combination,c.Code,s.SubjectName Subject,c.Status FROM tblschoolcombinations c JOIN tblpathwaytracks t ON t.id=c.TrackId JOIN tblpathways p ON p.id=t.PathwayId JOIN tblschoolcombinationsubjects cs ON cs.CombinationId=c.id JOIN tblsubjects s ON s.id=cs.SubjectId WHERE c.AcademicYearId=? ORDER BY p.Name,t.Name,c.Name,s.SubjectName',[$year]);
      case 'assessments':return cbe_rows($db,"SELECT a.id,a.Title,ty.Name Type,sub.SubjectName Subject,CONCAT(c.ClassName,' ',c.Section) Class,u.FullName Teacher,a.AssessmentDate Date,a.Status,(SELECT COUNT(*) FROM tblstudentsubjects ss JOIN tblstudents st ON st.StudentId=ss.StudentId AND st.ClassId=ss.ClassId AND st.Status=1 WHERE ss.ClassId=a.ClassId AND ss.SubjectId=a.SubjectId AND ss.AcademicYearId=a.AcademicYearId AND ss.Status=1) Expected,(SELECT COUNT(*) FROM tblassessmentresults r WHERE r.AssessmentId=a.id) Recorded FROM tblassessments a JOIN tblassessmenttypes ty ON ty.id=a.AssessmentTypeId JOIN tblsubjects sub ON sub.id=a.SubjectId JOIN tblclasses c ON c.id=a.ClassId JOIN tblusers u ON u.id=a.TeacherId WHERE $w ORDER BY a.AssessmentDate DESC",$p);
      case 'performance':return cbe_rows($db,"SELECT s.StudentName Student,s.RollId Admission,g.Name Grade,CONCAT(c.ClassName,' ',c.Section) Class,sub.SubjectName Subject,u.FullName Teacher,t.TermName Term,a.Title Assessment,a.AssessmentDate Date,r.Score,a.MaximumScore Maximum,ROUND(100*r.Score/NULLIF(a.MaximumScore,0),2) Percentage,pl.Name PerformanceLevel,r.Evidence FROM tblassessments a JOIN tblassessmentresults r ON r.AssessmentId=a.id JOIN tblstudents s ON s.StudentId=r.StudentId JOIN tblclasses c ON c.id=a.ClassId LEFT JOIN tblgrades g ON g.id=c.GradeId JOIN tblsubjects sub ON sub.id=a.SubjectId JOIN tblusers u ON u.id=a.TeacherId JOIN tblterms t ON t.id=a.TermId LEFT JOIN tblperformancelevels pl ON pl.id=r.PerformanceLevelId WHERE $w ORDER BY a.AssessmentDate,s.StudentName",$p);
      case 'coverage':return cbe_rows($db,"SELECT u.FullName Teacher,CONCAT(c.ClassName,' ',c.Section) Class,s.SubjectName Subject,a.ContentReference Content,a.ExpectedProgress Expected,a.ActualProgress Actual,CASE WHEN a.ActualProgress>=100 THEN 'COMPLETED' WHEN a.ActualProgress>=a.ExpectedProgress THEN 'ON TRACK' ELSE 'BEHIND' END Status,a.ReportDate Date,a.Notes FROM tblcurriculumcoverage a JOIN tblusers u ON u.id=a.TeacherId JOIN tblclasses c ON c.id=a.ClassId JOIN tblsubjects s ON s.id=a.SubjectId WHERE $w AND NOT EXISTS(SELECT 1 FROM tblcurriculumcoverage newer WHERE newer.TeacherId=a.TeacherId AND newer.ClassId=a.ClassId AND newer.SubjectId=a.SubjectId AND newer.AcademicYearId=a.AcademicYearId AND newer.TermId=a.TermId AND newer.ContentReference=a.ContentReference AND (newer.ReportDate>a.ReportDate OR (newer.ReportDate=a.ReportDate AND newer.id>a.id))) ORDER BY a.ReportDate DESC",$p);
      case 'interventions':return cbe_rows($db,"SELECT a.id,s.StudentName Student,sub.SubjectName Subject,u.FullName Teacher,a.Reason,a.ActionPlan Action,a.ReviewDate Review,a.Status,a.ReviewNotes FROM tblacademicinterventions a JOIN tblstudents s ON s.StudentId=a.StudentId JOIN tblsubjects sub ON sub.id=a.SubjectId JOIN tblusers u ON u.id=a.TeacherId WHERE $w ORDER BY a.ReviewDate",$p);
      case 'unallocated':return cbe_rows($db,'SELECT s.StudentName Student,s.RollId Admission,CONCAT(c.ClassName," ",c.Section) Class FROM tblstudents s LEFT JOIN tblclasses c ON c.id=s.ClassId WHERE s.Status=1 AND (?=0 OR s.ClassId=?) AND (?=0 OR s.StudentId=?) AND NOT EXISTS(SELECT 1 FROM tblstudentsubjects ss WHERE ss.StudentId=s.StudentId AND ss.ClassId=s.ClassId AND ss.AcademicYearId=? AND ss.Status=1) ORDER BY s.StudentName',[$class,$class,$student,$student,$year]);
      case 'legacy':return cbe_rows($db,"SELECT s.StudentName Student,CONCAT(c.ClassName,' ',c.Section) Class,sub.SubjectName Subject,t.TermName Term,a.ExamName Exam,r.marks Marks,a.Status FROM tblexams a JOIN tblresult r ON r.ExamId=a.id JOIN tblstudents s ON s.StudentId=r.StudentId JOIN tblsubjects sub ON sub.id=r.SubjectId JOIN tblclasses c ON c.id=r.ClassId JOIN tblterms t ON t.id=a.TermId WHERE $w ORDER BY a.id,s.StudentName",$p);
    }throw new DomainException('Invalid report.');
}
