<?php
if(!$cbeTeacherPortal) {
 echo '<p><a href="dean-timetable-setup.php">Configure rooms and school periods</a> · <a href="dean-class-timetable.php">Class timetable publication</a> · <a href="dean-exam-timetable.php">Exam timetable publication</a></p>';
 $kind=$_GET['kind']??'lesson';$table=$kind==='exam'?'tblexamtimetableentries':'tblclasstimetableentries';$v=$edit?cbe_one($dbh,"SELECT * FROM $table WHERE id=?",[$edit]):$defaults;
 if($kind==='exam'&&$edit&&$v)$v['Invigilators']=timetable_exam_invigilators($dbh,$edit);
 $days='enum:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday';
 cbe_form($dbh,'Create / Edit Lesson','lesson',['AcademicYearId'=>'years','TermId'=>'terms','ClassId'=>'classes','SubjectId'=>'subjects','TeacherId'=>'teachers','RoomId'=>'rooms?','DayOfWeek'=>$days,'StartTime'=>'text','EndTime'=>'text','Status'=>'enum:draft|ready_for_review|approved|published|updated|cancelled|archived','ChangeReason'=>'textarea'],$kind==='lesson'?($v?:$defaults):$defaults);
 cbe_form($dbh,'Create / Edit Examination Session and Invigilators','exam_session',['ExamId'=>'exams','ClassId'=>'classes','SubjectId'=>'subjects','RoomId'=>'rooms?','Invigilators'=>'teachers[]','ExamDate'=>'date','StartTime'=>'text','EndTime'=>'text','Status'=>'enum:draft|ready_for_review|approved|published|updated|cancelled|archived','ChangeReason'=>'textarea'],$kind==='exam'?($v?:$defaults):$defaults);
 echo '<p>Enter times as HH:MM. Scheduling rejects overlapping classes, teachers and rooms. Exam checks span all examination periods on the same date.</p>';
}
$lp=[$year,$term,$term,$class,$class,$teacher,$teacher,$cbeTeacherPortal?1:0,$teacher,$subject,$subject,$cbeTeacherPortal?1:0];
echo '<h3>Weekly Timetable</h3>';cbe_table(cbe_rows($dbh,'SELECT e.id,CONCAT(c.ClassName," ",c.Section) Class,s.SubjectName Subject,u.FullName Teacher,e.DayOfWeek Day,e.StartTime Start,e.EndTime End,r.RoomName Room,e.Status FROM tblclasstimetableentries e JOIN tblclasses c ON c.id=e.ClassId JOIN tblsubjects s ON s.id=e.SubjectId LEFT JOIN tblusers u ON u.id=e.TeacherId LEFT JOIN tblrooms r ON r.id=e.RoomId WHERE e.AcademicYearId=? AND (?=0 OR e.TermId=?) AND (?=0 OR e.ClassId=?) AND (?=0 OR e.TeacherId=? OR (?=1 AND EXISTS(SELECT 1 FROM tblclassteacherassignments ca WHERE ca.ClassId=e.ClassId AND ca.AcademicYearId=e.AcademicYearId AND ca.TeacherId=? AND ca.Status=1))) AND (?=0 OR e.SubjectId=?) AND (?=0 OR e.Status="published") ORDER BY FIELD(e.DayOfWeek,"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"),e.StartTime',$lp),$cbeTeacherPortal?null:$base.'?area=timetable&kind=lesson&year='.$year.'&term='.$term.'&id=');
echo '<h3>Examination / Invigilation Timetable</h3>';cbe_table(cbe_rows($dbh,'SELECT e.id,x.ExamName Exam,CONCAT(c.ClassName," ",c.Section) Class,s.SubjectName Subject,e.ExamDate Date,e.StartTime Start,e.EndTime End,r.RoomName Room,(SELECT GROUP_CONCAT(u.FullName ORDER BY u.FullName SEPARATOR ", ") FROM tblusers u WHERE u.id=e.InvigilatorId OR EXISTS(SELECT 1 FROM tblexaminvigilators i WHERE i.SessionId=e.id AND i.TeacherId=u.id)) Invigilators,e.Status FROM tblexamtimetableentries e JOIN tblexams x ON x.id=e.ExamId JOIN tblclasses c ON c.id=e.ClassId JOIN tblsubjects s ON s.id=e.SubjectId LEFT JOIN tblrooms r ON r.id=e.RoomId WHERE x.AcademicYearId=? AND (?=0 OR x.TermId=?) AND (?=0 OR e.ClassId=?) AND (?=0 OR e.InvigilatorId=? OR EXISTS(SELECT 1 FROM tblexaminvigilators i WHERE i.SessionId=e.id AND i.TeacherId=?) OR (?=1 AND EXISTS(SELECT 1 FROM tblclassteacherassignments ca WHERE ca.ClassId=e.ClassId AND ca.AcademicYearId=x.AcademicYearId AND ca.TeacherId=? AND ca.Status=1))) AND (?=0 OR e.SubjectId=?) AND (?=0 OR e.Status="published") ORDER BY e.ExamDate,e.StartTime',[$year,$term,$term,$class,$class,$teacher,$teacher,$teacher,$cbeTeacherPortal?1:0,$teacher,$subject,$subject,$cbeTeacherPortal?1:0]),$cbeTeacherPortal?null:$base.'?area=timetable&kind=exam&year='.$year.'&id=');
